### ISSUE TITLE
学长求一下中科院随机过程期末考试试题

### ISSUE THREAD

**Issue by linkedlist771** [yimingli1998/RDF#1]
学长求一下中科院随机过程期末考试试题。

**Comment by yimingli1998** [comment]
你好，给我个邮箱，我发你邮箱吧

LLinkedlist ***@***.***> 于 2024年1月4日周四 上午6:21写道：

**Comment by linkedlist771** [comment]
`213193509seu@gmail.com`  十分感谢学长。
