### ISSUE TITLE
Do I need voxel files to train my custom robot in RDF?

### ISSUE THREAD

**Issue by sm3304love** [yimingli1998/RDF#2]
I want to calculate the RDF of my custom robot. When I checked the code inside panda_layer, I confirmed that the voxel file and sdf file were being used in different codes. Do I need a voxel file for learning?

**Comment by yimingli1998** [comment]
Hi, the voxel file is a re-meshed version of the original mesh files. However, there is no need to use it for learning. You can directly use stl files in meshes/visual to build the panda_layer as well as RDF.
