### ISSUE TITLE
Request an example of collision avoidance using SDF

### ISSUE THREAD

**Issue by sm3304love** [yimingli1998/RDF#3]
I am trying to do motion planning for a panda robot based on optimization. I would also like to implement obstacle avoidance using RDF, but there doesn't seem to be any equations or examples for collision avoidance in the paper or on github. If you don't mind, can you add an example for this?

**Comment by yimingli1998** [comment]
Hi, thanks for your interest! I have added a simple example for collision avoidance by using the gradient of RDF with respect to the joint configuration. You can find it at https://github.com/yimingli1998/RDF/blob/master/collision_avoidance_example/collision_avoidance_example.py

Let me know if you have any further questions
